.TH LIBCOOPGAMMA_SET_GAMMA_RECV 3 LIBCOOPGAMMA
.SH "NAME"
libcoopgamma_set_gamma_recv - Check whether a request to modify the filter table for a CRTC succeeded
.SH "SYNOPSIS"
.nf
#include <libcoopgamma.h>

int libcoopgamma_set_gamma_recv(libcoopgamma_context_t *restrict \fIctx\fP,
                                libcoopgamma_async_context_t *restrict \fIasync\fP);
.fi
.P
Link with
.IR -lcoopgamma .
.SH "DESCRIPTION"
The
.BR libcoopgamma_set_gamma_recv ()
function parses the response for the requests
sent using the
.BR libcoopgamma_set_gamma_send ()
function with the same
.I ctx
and
.I async
arguments. The
.I async
must have been selected by the last call to the
.BR libcoopgamma_synchronise (3)
function.
.SH "RETURN VALUES"
Upon successful completion, the
.BR libcoopgamma_set_gamma_recv ()
function returns 0. On error, -1 is returned and
.I errno
is set appropriately.
.SH "ERRORS"
The
.BR libcoopgamma_set_gamma_recv ()
function may fail for any reason specified for
.BR malloc (3).
The function may also fail for the following reasons:
.TP
.B EBADMSG
The received message was corrupt.
.SH "SEE ALSO"
.BR libcoopgamma.h (0),
.BR libcoopgamma_async_context_destroy (3),
.BR libcoopgamma_synchronise (3),
.BR libcoopgamma_set_gamma_send (3),
.BR libcoopgamma_set_gamma_sync (3),
.BR libcoopgamma_get_crtcs_recv (3),
.BR libcoopgamma_get_gamma_info_recv (3),
.BR libcoopgamma_get_gamma_recv (3)
