MAN0 =\
	libcoopgamma.h.0

MAN3=\
	libcoopgamma_async_context_destroy.3\
	libcoopgamma_async_context_initialise.3\
	libcoopgamma_async_context_marshal.3\
	libcoopgamma_async_context_unmarshal.3\
	libcoopgamma_connect.3\
	libcoopgamma_context_destroy.3\
	libcoopgamma_context_initialise.3\
	libcoopgamma_context_marshal.3\
	libcoopgamma_context_unmarshal.3\
	libcoopgamma_crtc_info_destroy.3\
	libcoopgamma_crtc_info_initialise.3\
	libcoopgamma_crtc_info_marshal.3\
	libcoopgamma_crtc_info_unmarshal.3\
	libcoopgamma_error_destroy.3\
	libcoopgamma_error_initialise.3\
	libcoopgamma_error_marshal.3\
	libcoopgamma_error_unmarshal.3\
	libcoopgamma_filter_destroy.3\
	libcoopgamma_filter_initialise.3\
	libcoopgamma_filter_marshal.3\
	libcoopgamma_filter_query_destroy.3\
	libcoopgamma_filter_query_initialise.3\
	libcoopgamma_filter_query_marshal.3\
	libcoopgamma_filter_query_unmarshal.3\
	libcoopgamma_filter_table_destroy.3\
	libcoopgamma_filter_table_initialise.3\
	libcoopgamma_filter_table_marshal.3\
	libcoopgamma_filter_table_unmarshal.3\
	libcoopgamma_filter_unmarshal.3\
	libcoopgamma_flush.3\
	libcoopgamma_get_crtcs_recv.3\
	libcoopgamma_get_crtcs_send.3\
	libcoopgamma_get_crtcs_sync.3\
	libcoopgamma_get_gamma_info_recv.3\
	libcoopgamma_get_gamma_info_send.3\
	libcoopgamma_get_gamma_info_sync.3\
	libcoopgamma_get_gamma_recv.3\
	libcoopgamma_get_gamma_send.3\
	libcoopgamma_get_gamma_sync.3\
	libcoopgamma_get_method_and_site.3\
	libcoopgamma_get_methods.3\
	libcoopgamma_get_pid_file.3\
	libcoopgamma_get_socket_file.3\
	libcoopgamma_queried_filter_destroy.3\
	libcoopgamma_queried_filter_initialise.3\
	libcoopgamma_queried_filter_marshal.3\
	libcoopgamma_queried_filter_unmarshal.3\
	libcoopgamma_ramps_destroy.3\
	libcoopgamma_ramps_initialise.3\
	libcoopgamma_ramps_marshal.3\
	libcoopgamma_ramps_unmarshal.3\
	libcoopgamma_set_gamma_recv.3\
	libcoopgamma_set_gamma_send.3\
	libcoopgamma_set_gamma_sync.3\
	libcoopgamma_set_nonblocking.3\
	libcoopgamma_skip_message.3\
	libcoopgamma_synchronise.3

MAN7 =\
	libcoopgamma.7
