.TH LIBCOOPGAMMA_FILTER_TABLE_INITIALISE 3 LIBCOOPGAMMA
.SH "NAME"
libcoopgamma_filter_table_initialise - Initialise a libcoopgamma_filter_table_t
.SH "SYNOPSIS"
.nf
#include <libcoopgamma.h>

int libcoopgamma_filter_table_initialise(libcoopgamma_filter_table_t *restrict \fIthis\fP);
.fi
.P
Link with
.IR -lcoopgamma .
.SH "DESCRIPTION"
The
.BR libcoopgamma_filter_table_initialise ()
function initialises
.IR this .
.SH "RETURN VALUES"
The
.BR libcoopgamma_filter_table_initialise ()
returns 0 on success. On error, -1 is returned and
.I errno
is set appropriately.
.SH "ERRORS"
There are no errors specified for the
.BR libcoopgamma_filter_table_initialise ()
function.
.SH "SEE ALSO"
.BR libcoopgamma.h (0),
.BR libcoopgamma_filter_table_destroy (3),
.BR libcoopgamma_filter_table_marshal (3),
.BR libcoopgamma_ramps_initialise (3),
.BR libcoopgamma_filter_initialise (3),
.BR libcoopgamma_crtc_info_initialise (3),
.BR libcoopgamma_filter_query_initialise (3),
.BR libcoopgamma_queried_filter_initialise (3),
.BR libcoopgamma_error_initialise (3),
.BR libcoopgamma_context_initialise (3),
.BR libcoopgamma_async_context_initialise (3)
