.TH LIBCOOPGAMMA_CONTEXT_DESTROY 3 LIBCOOPGAMMA
.SH "NAME"
libcoopgamma_context_destroy - Deinitialise a libcoopgamma_context_t
.SH "SYNOPSIS"
.nf
#include <libcoopgamma.h>

void libcoopgamma_context_destroy(libcoopgamma_context_t *restrict \fIthis\fP, int \fIdisconnect\fP);
.fi
.P
Link with
.IR -lcoopgamma .
.SH "DESCRIPTION"
The
.BR libcoopgamma_context_destroy ()
function releases all resources allocated
to
.IR this .
The function does however not free the
allocation of the pointer
.IR this
itself.
.P
If and only if
.I disconnect
is a non-zero value, the function will
disconnect from the coopgamma server.
.SH "SEE ALSO"
.BR libcoopgamma_context_initialise (3),
.BR libcoopgamma_context_marshal (3),
.BR libcoopgamma_ramps_destroy (3),
.BR libcoopgamma_filter_destroy (3),
.BR libcoopgamma_crtc_info_destroy (3),
.BR libcoopgamma_filter_query_destroy (3),
.BR libcoopgamma_queried_filter_destroy (3),
.BR libcoopgamma_filter_table_destroy (3),
.BR libcoopgamma_error_destroy (3),
.BR libcoopgamma_async_context_destroy (3)
